spring:
  application:
    name: mcp        # Disable banner
  ai:
    mcp:
      server:
        type: SYNC
        protocol: STATELESS
        name: monoservice-mcp # Server name
        version: 0.0.1         # Server version
        streamable-http:
          mcp-endpoint: /mcp

server:
  port: 8082


backend:
  monoservices:
    url: http://localhost:8081/mono_services/v1

logging:
  level:
    org.springframework.ai: DEBUG

